class IndexCreatedUpdatedFields < ActiveRecord::Migration
  def up
    add_index :alert_guideline_steps, [:created_at, :updated_at]
    add_index :alert_responses, [:created_at, :updated_at]
    add_index :alerts, [:created_at, :updated_at]
    add_index :body_systems, [:created_at, :updated_at]
    add_index :checklists, [:created_at, :updated_at]
    add_index :guideline_actions, [:created_at, :updated_at]
    add_index :guideline_steps, [:created_at, :updated_at]
    add_index :guidelines, [:created_at, :updated_at]
    add_index :locations, [:created_at, :updated_at]
    add_index :observations, [:created_at, :updated_at]
    add_index :patient_checklists, [:created_at, :updated_at]
    add_index :patient_flowsheet_rows, [:created_at, :updated_at]
    add_index :patient_flowsheets, [:created_at, :updated_at]
    add_index :patient_guideline_actions, [:created_at, :updated_at]
    add_index :patient_guideline_steps, [:created_at, :updated_at]
    add_index :patient_guidelines, [:created_at, :updated_at]
    add_index :patient_locations, [:created_at, :updated_at]
    add_index :patients, [:created_at, :updated_at]
    add_index :problems, [:created_at, :updated_at]
    add_index :questions, [:created_at, :updated_at]
    add_index :responses, [:created_at, :updated_at]
    add_index :risk_profiles, [:created_at, :updated_at]
    add_index :user_sessions, [:created_at, :updated_at]
    add_index :users, [:created_at, :updated_at]
    add_index :value_set_members, [:created_at, :updated_at]
    add_index :value_sets, [:created_at, :updated_at]
  end

  def down
    remove_index :alert_guideline_steps, [:created_at, :updated_at]
    remove_index :alert_responses, [:created_at, :updated_at]
    remove_index :alerts, [:created_at, :updated_at]
    remove_index :body_systems, [:created_at, :updated_at]
    remove_index :checklists, [:created_at, :updated_at]
    remove_index :guideline_actions, [:created_at, :updated_at]
    remove_index :guideline_steps, [:created_at, :updated_at]
    remove_index :guidelines, [:created_at, :updated_at]
    remove_index :locations, [:created_at, :updated_at]
    remove_index :observations, [:created_at, :updated_at]
    remove_index :patient_checklists, [:created_at, :updated_at]
    remove_index :patient_flowsheet_rows, [:created_at, :updated_at]
    remove_index :patient_flowsheets, [:created_at, :updated_at]
    remove_index :patient_guideline_actions, [:created_at, :updated_at]
    remove_index :patient_guideline_steps, [:created_at, :updated_at]
    remove_index :patient_guidelines, [:created_at, :updated_at]
    remove_index :patient_locations, [:created_at, :updated_at]
    remove_index :patients, [:created_at, :updated_at]
    remove_index :problems, [:created_at, :updated_at]
    remove_index :questions, [:created_at, :updated_at]
    remove_index :responses, [:created_at, :updated_at]
    remove_index :risk_profiles, [:created_at, :updated_at]
    remove_index :user_sessions, [:created_at, :updated_at]
    remove_index :users, [:created_at, :updated_at]
    remove_index :value_set_members, [:created_at, :updated_at]
    remove_index :value_sets, [:created_at, :updated_at]
  end
end
