require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GuidelinesController do

  # This should return the minimal set of attributes required to create a valid
  # Guideline. As you add validations to Guideline, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GuidelinesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all guidelines as @guidelines" do
      guideline = Guideline.create! valid_attributes
      get :index, {}, valid_session
      assigns(:guidelines).should eq([guideline])
    end
  end

  describe "GET show" do
    it "assigns the requested guideline as @guideline" do
      guideline = Guideline.create! valid_attributes
      get :show, {:id => guideline.to_param}, valid_session
      assigns(:guideline).should eq(guideline)
    end
  end

  describe "GET new" do
    it "assigns a new guideline as @guideline" do
      get :new, {}, valid_session
      assigns(:guideline).should be_a_new(Guideline)
    end
  end

  describe "GET edit" do
    it "assigns the requested guideline as @guideline" do
      guideline = Guideline.create! valid_attributes
      get :edit, {:id => guideline.to_param}, valid_session
      assigns(:guideline).should eq(guideline)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Guideline" do
        expect {
          post :create, {:guideline => valid_attributes}, valid_session
        }.to change(Guideline, :count).by(1)
      end

      it "assigns a newly created guideline as @guideline" do
        post :create, {:guideline => valid_attributes}, valid_session
        assigns(:guideline).should be_a(Guideline)
        assigns(:guideline).should be_persisted
      end

      it "redirects to the created guideline" do
        post :create, {:guideline => valid_attributes}, valid_session
        response.should redirect_to(Guideline.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved guideline as @guideline" do
        # Trigger the behavior that occurs when invalid params are submitted
        Guideline.any_instance.stub(:save).and_return(false)
        post :create, {:guideline => { "name" => "invalid value" }}, valid_session
        assigns(:guideline).should be_a_new(Guideline)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Guideline.any_instance.stub(:save).and_return(false)
        post :create, {:guideline => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested guideline" do
        guideline = Guideline.create! valid_attributes
        # Assuming there are no other guidelines in the database, this
        # specifies that the Guideline created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Guideline.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => guideline.to_param, :guideline => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested guideline as @guideline" do
        guideline = Guideline.create! valid_attributes
        put :update, {:id => guideline.to_param, :guideline => valid_attributes}, valid_session
        assigns(:guideline).should eq(guideline)
      end

      it "redirects to the guideline" do
        guideline = Guideline.create! valid_attributes
        put :update, {:id => guideline.to_param, :guideline => valid_attributes}, valid_session
        response.should redirect_to(guideline)
      end
    end

    describe "with invalid params" do
      it "assigns the guideline as @guideline" do
        guideline = Guideline.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Guideline.any_instance.stub(:save).and_return(false)
        put :update, {:id => guideline.to_param, :guideline => { "name" => "invalid value" }}, valid_session
        assigns(:guideline).should eq(guideline)
      end

      it "re-renders the 'edit' template" do
        guideline = Guideline.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Guideline.any_instance.stub(:save).and_return(false)
        put :update, {:id => guideline.to_param, :guideline => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested guideline" do
      guideline = Guideline.create! valid_attributes
      expect {
        delete :destroy, {:id => guideline.to_param}, valid_session
      }.to change(Guideline, :count).by(-1)
    end

    it "redirects to the guidelines list" do
      guideline = Guideline.create! valid_attributes
      delete :destroy, {:id => guideline.to_param}, valid_session
      response.should redirect_to(guidelines_url)
    end
  end

end
