require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GuidelineStepsController do

  # This should return the minimal set of attributes required to create a valid
  # GuidelineStep. As you add validations to GuidelineStep, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GuidelineStepsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all guideline_steps as @guideline_steps" do
      guideline_step = GuidelineStep.create! valid_attributes
      get :index, {}, valid_session
      assigns(:guideline_steps).should eq([guideline_step])
    end
  end

  describe "GET show" do
    it "assigns the requested guideline_step as @guideline_step" do
      guideline_step = GuidelineStep.create! valid_attributes
      get :show, {:id => guideline_step.to_param}, valid_session
      assigns(:guideline_step).should eq(guideline_step)
    end
  end

  describe "GET new" do
    it "assigns a new guideline_step as @guideline_step" do
      get :new, {}, valid_session
      assigns(:guideline_step).should be_a_new(GuidelineStep)
    end
  end

  describe "GET edit" do
    it "assigns the requested guideline_step as @guideline_step" do
      guideline_step = GuidelineStep.create! valid_attributes
      get :edit, {:id => guideline_step.to_param}, valid_session
      assigns(:guideline_step).should eq(guideline_step)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GuidelineStep" do
        expect {
          post :create, {:guideline_step => valid_attributes}, valid_session
        }.to change(GuidelineStep, :count).by(1)
      end

      it "assigns a newly created guideline_step as @guideline_step" do
        post :create, {:guideline_step => valid_attributes}, valid_session
        assigns(:guideline_step).should be_a(GuidelineStep)
        assigns(:guideline_step).should be_persisted
      end

      it "redirects to the created guideline_step" do
        post :create, {:guideline_step => valid_attributes}, valid_session
        response.should redirect_to(GuidelineStep.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved guideline_step as @guideline_step" do
        # Trigger the behavior that occurs when invalid params are submitted
        GuidelineStep.any_instance.stub(:save).and_return(false)
        post :create, {:guideline_step => { "name" => "invalid value" }}, valid_session
        assigns(:guideline_step).should be_a_new(GuidelineStep)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GuidelineStep.any_instance.stub(:save).and_return(false)
        post :create, {:guideline_step => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested guideline_step" do
        guideline_step = GuidelineStep.create! valid_attributes
        # Assuming there are no other guideline_steps in the database, this
        # specifies that the GuidelineStep created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GuidelineStep.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => guideline_step.to_param, :guideline_step => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested guideline_step as @guideline_step" do
        guideline_step = GuidelineStep.create! valid_attributes
        put :update, {:id => guideline_step.to_param, :guideline_step => valid_attributes}, valid_session
        assigns(:guideline_step).should eq(guideline_step)
      end

      it "redirects to the guideline_step" do
        guideline_step = GuidelineStep.create! valid_attributes
        put :update, {:id => guideline_step.to_param, :guideline_step => valid_attributes}, valid_session
        response.should redirect_to(guideline_step)
      end
    end

    describe "with invalid params" do
      it "assigns the guideline_step as @guideline_step" do
        guideline_step = GuidelineStep.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GuidelineStep.any_instance.stub(:save).and_return(false)
        put :update, {:id => guideline_step.to_param, :guideline_step => { "name" => "invalid value" }}, valid_session
        assigns(:guideline_step).should eq(guideline_step)
      end

      it "re-renders the 'edit' template" do
        guideline_step = GuidelineStep.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GuidelineStep.any_instance.stub(:save).and_return(false)
        put :update, {:id => guideline_step.to_param, :guideline_step => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested guideline_step" do
      guideline_step = GuidelineStep.create! valid_attributes
      expect {
        delete :destroy, {:id => guideline_step.to_param}, valid_session
      }.to change(GuidelineStep, :count).by(-1)
    end

    it "redirects to the guideline_steps list" do
      guideline_step = GuidelineStep.create! valid_attributes
      delete :destroy, {:id => guideline_step.to_param}, valid_session
      response.should redirect_to(guideline_steps_url)
    end
  end

end
