require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PatientGuidelinesController do

  # This should return the minimal set of attributes required to create a valid
  # PatientGuideline. As you add validations to PatientGuideline, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "guideline_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PatientGuidelinesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all patient_guidelines as @patient_guidelines" do
      patient_guideline = PatientGuideline.create! valid_attributes
      get :index, {}, valid_session
      assigns(:patient_guidelines).should eq([patient_guideline])
    end
  end

  describe "GET show" do
    it "assigns the requested patient_guideline as @patient_guideline" do
      patient_guideline = PatientGuideline.create! valid_attributes
      get :show, {:id => patient_guideline.to_param}, valid_session
      assigns(:patient_guideline).should eq(patient_guideline)
    end
  end

  describe "GET new" do
    it "assigns a new patient_guideline as @patient_guideline" do
      get :new, {}, valid_session
      assigns(:patient_guideline).should be_a_new(PatientGuideline)
    end
  end

  describe "GET edit" do
    it "assigns the requested patient_guideline as @patient_guideline" do
      patient_guideline = PatientGuideline.create! valid_attributes
      get :edit, {:id => patient_guideline.to_param}, valid_session
      assigns(:patient_guideline).should eq(patient_guideline)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PatientGuideline" do
        expect {
          post :create, {:patient_guideline => valid_attributes}, valid_session
        }.to change(PatientGuideline, :count).by(1)
      end

      it "assigns a newly created patient_guideline as @patient_guideline" do
        post :create, {:patient_guideline => valid_attributes}, valid_session
        assigns(:patient_guideline).should be_a(PatientGuideline)
        assigns(:patient_guideline).should be_persisted
      end

      it "redirects to the created patient_guideline" do
        post :create, {:patient_guideline => valid_attributes}, valid_session
        response.should redirect_to(PatientGuideline.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved patient_guideline as @patient_guideline" do
        # Trigger the behavior that occurs when invalid params are submitted
        PatientGuideline.any_instance.stub(:save).and_return(false)
        post :create, {:patient_guideline => { "guideline_id" => "invalid value" }}, valid_session
        assigns(:patient_guideline).should be_a_new(PatientGuideline)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PatientGuideline.any_instance.stub(:save).and_return(false)
        post :create, {:patient_guideline => { "guideline_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested patient_guideline" do
        patient_guideline = PatientGuideline.create! valid_attributes
        # Assuming there are no other patient_guidelines in the database, this
        # specifies that the PatientGuideline created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PatientGuideline.any_instance.should_receive(:update_attributes).with({ "guideline_id" => "1" })
        put :update, {:id => patient_guideline.to_param, :patient_guideline => { "guideline_id" => "1" }}, valid_session
      end

      it "assigns the requested patient_guideline as @patient_guideline" do
        patient_guideline = PatientGuideline.create! valid_attributes
        put :update, {:id => patient_guideline.to_param, :patient_guideline => valid_attributes}, valid_session
        assigns(:patient_guideline).should eq(patient_guideline)
      end

      it "redirects to the patient_guideline" do
        patient_guideline = PatientGuideline.create! valid_attributes
        put :update, {:id => patient_guideline.to_param, :patient_guideline => valid_attributes}, valid_session
        response.should redirect_to(patient_guideline)
      end
    end

    describe "with invalid params" do
      it "assigns the patient_guideline as @patient_guideline" do
        patient_guideline = PatientGuideline.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PatientGuideline.any_instance.stub(:save).and_return(false)
        put :update, {:id => patient_guideline.to_param, :patient_guideline => { "guideline_id" => "invalid value" }}, valid_session
        assigns(:patient_guideline).should eq(patient_guideline)
      end

      it "re-renders the 'edit' template" do
        patient_guideline = PatientGuideline.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PatientGuideline.any_instance.stub(:save).and_return(false)
        put :update, {:id => patient_guideline.to_param, :patient_guideline => { "guideline_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested patient_guideline" do
      patient_guideline = PatientGuideline.create! valid_attributes
      expect {
        delete :destroy, {:id => patient_guideline.to_param}, valid_session
      }.to change(PatientGuideline, :count).by(-1)
    end

    it "redirects to the patient_guidelines list" do
      patient_guideline = PatientGuideline.create! valid_attributes
      delete :destroy, {:id => patient_guideline.to_param}, valid_session
      response.should redirect_to(patient_guidelines_url)
    end
  end

end
