require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ValueSetMembersController do

  # This should return the minimal set of attributes required to create a valid
  # ValueSetMember. As you add validations to ValueSetMember, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "code" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ValueSetMembersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all value_set_members as @value_set_members" do
      value_set_member = ValueSetMember.create! valid_attributes
      get :index, {}, valid_session
      assigns(:value_set_members).should eq([value_set_member])
    end
  end

  describe "GET show" do
    it "assigns the requested value_set_member as @value_set_member" do
      value_set_member = ValueSetMember.create! valid_attributes
      get :show, {:id => value_set_member.to_param}, valid_session
      assigns(:value_set_member).should eq(value_set_member)
    end
  end

  describe "GET new" do
    it "assigns a new value_set_member as @value_set_member" do
      get :new, {}, valid_session
      assigns(:value_set_member).should be_a_new(ValueSetMember)
    end
  end

  describe "GET edit" do
    it "assigns the requested value_set_member as @value_set_member" do
      value_set_member = ValueSetMember.create! valid_attributes
      get :edit, {:id => value_set_member.to_param}, valid_session
      assigns(:value_set_member).should eq(value_set_member)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ValueSetMember" do
        expect {
          post :create, {:value_set_member => valid_attributes}, valid_session
        }.to change(ValueSetMember, :count).by(1)
      end

      it "assigns a newly created value_set_member as @value_set_member" do
        post :create, {:value_set_member => valid_attributes}, valid_session
        assigns(:value_set_member).should be_a(ValueSetMember)
        assigns(:value_set_member).should be_persisted
      end

      it "redirects to the created value_set_member" do
        post :create, {:value_set_member => valid_attributes}, valid_session
        response.should redirect_to(ValueSetMember.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved value_set_member as @value_set_member" do
        # Trigger the behavior that occurs when invalid params are submitted
        ValueSetMember.any_instance.stub(:save).and_return(false)
        post :create, {:value_set_member => { "code" => "invalid value" }}, valid_session
        assigns(:value_set_member).should be_a_new(ValueSetMember)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ValueSetMember.any_instance.stub(:save).and_return(false)
        post :create, {:value_set_member => { "code" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested value_set_member" do
        value_set_member = ValueSetMember.create! valid_attributes
        # Assuming there are no other value_set_members in the database, this
        # specifies that the ValueSetMember created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ValueSetMember.any_instance.should_receive(:update_attributes).with({ "code" => "MyString" })
        put :update, {:id => value_set_member.to_param, :value_set_member => { "code" => "MyString" }}, valid_session
      end

      it "assigns the requested value_set_member as @value_set_member" do
        value_set_member = ValueSetMember.create! valid_attributes
        put :update, {:id => value_set_member.to_param, :value_set_member => valid_attributes}, valid_session
        assigns(:value_set_member).should eq(value_set_member)
      end

      it "redirects to the value_set_member" do
        value_set_member = ValueSetMember.create! valid_attributes
        put :update, {:id => value_set_member.to_param, :value_set_member => valid_attributes}, valid_session
        response.should redirect_to(value_set_member)
      end
    end

    describe "with invalid params" do
      it "assigns the value_set_member as @value_set_member" do
        value_set_member = ValueSetMember.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ValueSetMember.any_instance.stub(:save).and_return(false)
        put :update, {:id => value_set_member.to_param, :value_set_member => { "code" => "invalid value" }}, valid_session
        assigns(:value_set_member).should eq(value_set_member)
      end

      it "re-renders the 'edit' template" do
        value_set_member = ValueSetMember.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ValueSetMember.any_instance.stub(:save).and_return(false)
        put :update, {:id => value_set_member.to_param, :value_set_member => { "code" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested value_set_member" do
      value_set_member = ValueSetMember.create! valid_attributes
      expect {
        delete :destroy, {:id => value_set_member.to_param}, valid_session
      }.to change(ValueSetMember, :count).by(-1)
    end

    it "redirects to the value_set_members list" do
      value_set_member = ValueSetMember.create! valid_attributes
      delete :destroy, {:id => value_set_member.to_param}, valid_session
      response.should redirect_to(value_set_members_url)
    end
  end

end
